Update dependencies
sdiehl/protolude pull request #143
Opened 2023-05-18 22:17 UTC by erikd

Builds correctly with ghc-9.6.1

Would also love to see a new release with these changes.

These changes will allow us to drop a bunch of `allow-newer` stanzas in the `cabal.project` file of out `ghc-9.6` builds.

2023-05-18 22:32 UTC, erikd commented
I would also be happy to become a project collaborator for `protolude` if you want me. I work for [IOHK/IOG](http://github.com/input-output-hk) and we use `protolude` at the bottom of our software stack.

2023-05-21 22:41 UTC, erikd commented
It is possible to relax these constraints using a package revision on Hackage.

2023-05-22 05:47 UTC, andreasabel commented
@adamwespiser CI needs your intervention to run on this PR, it seems.

2023-06-12 22:55 UTC, erikd commented
@andreasabel Is this not suitable for a Hackage trustee metadata edit now?

2023-06-13 14:15 UTC, andreasabel requested changes

2023-06-13 14:15 UTC, andreasabel commented on protolude.cabal
> +    , base                 >=4.6  && <4.20
Should be `<4.19`.

2023-06-13 14:15 UTC, andreasabel commented on protolude.cabal
> +    , containers           >=0.5  && <0.8
Isn't the last `containers` 0.6.7 ?

2023-06-13 14:15 UTC, andreasabel commented
> @andreasabel Is this not suitable for a Hackage trustee metadata edit now?

Here you go: https://hackage.haskell.org/package/protolude-0.3.3/revisions/

2025-02-17 01:43 UTC, closed without merging